Q1. Write a function ‘factorial(n)’ to find the factorial of a given positive integer n. Using this
function, write a function ‘binom(n,k)’ to find the binomial coefficient (n/k) = n!/(k!(n-k)!)

In [1]:
def factorial(n): #function defination
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

def binom(n, k):
    return factorial(n) / (factorial(k) * factorial(n - k))


In [5]:
#fucntion calling
x= binom(7,4)
print ("The binomial coefficient is ", x)

The binomial coefficient is  35.0


Q2. Find three functions scripts named ‘equalFirstText(str1, str2, n)’,
‘equalLastText(str1,str2,n)’ and ‘equalFirstLastText(stt1,str2,n)’. These three functions checks whether in two given strings
(i) are the first ‘n’ characters the same or not,
(ii) are the last ‘n’ characters the same or not, and
(iii) are the first ‘n’ and last ‘n’ characters identical or not?

In [124]:
def equalFirstText(str1, str2, n): #function 1
    l=0
    if str1[:n].lower() == str2[:n].lower() :
        l=len(str1[:n])
    if l==n:
        print("Yes, the first",n,"characters are same.")
    else:
        print("No, the first",n,"characters are not same.")
        

def equalLastText(str1, str2, n): #function 2
    l=0
    if str1[-n:].lower() == str2[-n:].lower():
        l=len(str1[-n:])
    if l==n:
        print("Yes, the last",n,"characters are same.")
    else:
        print("No, the last",n,"characters are not same.")


def equalFirstLastText(str1, str2, n): #function 3
    l=0
    if str1[:n] == str2[:n] and str1[-n:] == str2[-n:]:
        l=len(str1[-n:])
    if l==n:
        print("Yes, the frist",n,"and last",n,"are same.")
    else:
        print("No, the first",n,"and last",n,"are not same.")
        


In [125]:
#calling fn 1
equalFirstText("Soumik","soumya",4)
equalFirstText("Goutami","soumya",3)
#calling fn 2
equalLastText("GoutaMI","soumya",3)
equalLastText("souMIK","rittik",2)
#calling fn 3
equalFirstLastText("Soutami","soasdami",2)
equalFirstLastText("Goutami","Gosoumya",3)

Yes, the first 4 characters are same.
No, the first 3 characters are not same.
No, the last 3 characters are not same.
Yes, the last 2 characters are same.
No, the first 2 and last 2 are not same.
No, the first 3 and last 3 are not same.


Q3. Write a Python program for the following:
    a) Generate random matrices A4×5, B5×3 and C3×4 of your choice.
    b) Compute the matrices G = AB, D = BC, E = D + AT, F = ABC and print them.
    c) Compute the inverse of matrix and eigenvalues and eigenvectors of F.
    d) Find the square root of the elements of the matrix A and print it.
    e) Find the natural logarithm of elements of the matrix BC and print it.
    f) Extract the sub matrix from A, which contains the elements from second row and third row and print it.
    g) Extract at least three sub matrices from B, of your choice and print them.
    h) Generate a random matrix R5×5 and a normalized random matrix S5×5 and calculate the matrices BCA+
        R and BCA − S and print them.
    i) Find the element by element multiplication and division of the matrices BC and AT

In [127]:
import numpy as np

In [178]:
#Q3>a
A = np.random.randint(1,10,size=(4, 5))
B = np.random.randint(1,10,size=(5, 3))
C = np.random.randint(1,10,size=(3, 4))

print("Matrix A (4x5):\n", A)
print("\nMatrix B (5x3):\n", B)
print("\nMatrix C (3x4):\n", C)


Matrix A (4x5):
 [[1 5 9 7 9]
 [6 2 6 5 3]
 [2 9 5 2 4]
 [2 9 2 6 3]]

Matrix B (5x3):
 [[8 3 7]
 [8 2 3]
 [1 3 8]
 [1 2 9]
 [8 6 7]]

Matrix C (3x4):
 [[3 3 6 8]
 [6 5 8 2]
 [4 7 5 7]]


In [179]:
#Q3>b
G=A@B
D=B@C
E=D+A.T
F=(A@B)@C
print("G: \n",G)
print("D: \n",D)
print("E: \n",E)
print("F: \n",F)

G: 
 [[136 108 220]
 [ 99  68 162]
 [127  67 127]
 [120  60 132]]
D: 
 [[ 70  88 107 119]
 [ 48  55  79  89]
 [ 53  74  70  70]
 [ 51  76  67  75]
 [ 88 103 131 125]]
E: 
 [[ 71  94 109 121]
 [ 53  57  88  98]
 [ 62  80  75  72]
 [ 58  81  69  81]
 [ 97 106 135 128]]
F: 
 [[1936 2488 2780 2844]
 [1353 1771 1948 2062]
 [1291 1605 1933 2039]
 [1248 1584 1860 2004]]


In [180]:
#Q3>c
F_inv = np.linalg.inv(F)
print("Inverse of F: \n", F_inv)

eival, eivec= np.linalg.eig(F)
print("Eigen Values of F: \n", eival)
print("Eigen Vectors of F: \n", eivec)

Inverse of F: 
 [[ 8.08438374e+12 -1.44934864e+13 -1.57845287e+13  1.95001176e+13]
 [-2.80898079e+12  5.03587241e+12  5.48445489e+12 -6.77546460e+12]
 [-4.69305328e+12  8.41359171e+12  9.16305269e+12 -1.13199835e+13]
 [ 1.54151385e+12 -2.76358852e+12 -3.00976183e+12  3.71824277e+12]]
Eigen Values of F: 
 [ 7.48339356e+03  1.16728564e+02 -1.25463061e-13  4.38778760e+01]
Eigen Vectors of F: 
 [[-0.64439518 -0.7438255  -0.81811396 -0.74277384]
 [-0.45687099 -0.35741007  0.28425994  0.44743184]
 [-0.43920206  0.41733363  0.47492209 -0.30093032]
 [-0.42793142  0.38054475 -0.15599631  0.3969039 ]]


In [181]:
#Q3>d
sq_A = np.sqrt(A)
print("The Square root of matrix A is : \n",sq_A)

The Square root of matrix A is : 
 [[1.         2.23606798 3.         2.64575131 3.        ]
 [2.44948974 1.41421356 2.44948974 2.23606798 1.73205081]
 [1.41421356 3.         2.23606798 1.41421356 2.        ]
 [1.41421356 3.         1.41421356 2.44948974 1.73205081]]


In [182]:
#Q3>e
BC = B@C
log_BC = np.log(BC)
print("Natural logarithm of BC is \n", log_BC)

Natural logarithm of BC is 
 [[4.24849524 4.47733681 4.67282883 4.77912349]
 [3.87120101 4.00733319 4.36944785 4.48863637]
 [3.97029191 4.30406509 4.24849524 4.24849524]
 [3.93182563 4.33073334 4.20469262 4.31748811]
 [4.47733681 4.63472899 4.87519732 4.82831374]]


In [183]:
#Q3>f
sub_mat = A[1:3]
print("The elements of sub matrix of A from second row and third row are: \n", sub_mat)

The elements of sub matrix of A from second row and third row are: 
 [[6 2 6 5 3]
 [2 9 5 2 4]]


In [184]:
#Q3>g
s1_B=B[:3]
s2_B=B[-2:,:3]
s3_B=B[2:4]
print("1st Sub Matrix is : \n", s1_B)
print("2nd Sub Matrix is : \n", s2_B)
print("3rd Sub Matrix is : \n", s3_B)

1st Sub Matrix is : 
 [[8 3 7]
 [8 2 3]
 [1 3 8]]
2nd Sub Matrix is : 
 [[1 2 9]
 [8 6 7]]
3rd Sub Matrix is : 
 [[1 3 8]
 [1 2 9]]


In [185]:
#Q3>h
R= np.random.randint(0,100,size=(5,5))
S= np.random.randint(0,100,size=(5,5))
print("The R is : \n", R)
print("The S is : \n", S)
S=S/np.linalg.norm(S)

BCA = B@C@A
plus= BCA+R
minus= BCA-S

print("The matrix BCA+R is : \n", plus)
print("The matrix BCA-S is : \n", minus)

The R is : 
 [[35 83 35 65  8]
 [43 58  2 90 34]
 [69 46 14 45  0]
 [51 82 51 31 28]
 [92 73  0 92 91]]
The S is : 
 [[77 14 23 36 20]
 [41 31 20 20 26]
 [60 28 52 75 42]
 [67  5 92 58 89]
 [86 35 57 72 12]]
The matrix BCA+R is : 
 [[1085 2643 1966 1923 1687]
 [ 757 1920 1337 1393 1214]
 [ 846 1719 1425 1346 1189]
 [ 842 1767 1451 1352 1208]
 [1310 3023 2315 2235 2091]]
The matrix BCA-S is : 
 [[1049.70559605 2559.94647201 1930.91206116 1857.8623566  1678.92353144]
 [ 713.84323946 1861.88147374 1334.92353144 1302.92353144 1179.90059088]
 [ 776.77059433 1672.89294402 1410.80118175 1300.71324291 1188.83941603]
 [ 790.74383033 1684.98088286 1399.64824464 1320.77824118 1179.65971492]
 [1217.6711852  2949.86618002 2314.78206461 2142.72471319 1999.95411887]]


In [186]:
multi=B@C * A.T
divi=B@C / A.T
print("The element by element multipliction is \n",multi)
print("The element by element division is \n",divi)

The element by element multipliction is 
 [[ 70 528 214 238]
 [240 110 711 801]
 [477 444 350 140]
 [357 380 134 450]
 [792 309 524 375]]
The element by element division is 
 [[70.         14.66666667 53.5        59.5       ]
 [ 9.6        27.5         8.77777778  9.88888889]
 [ 5.88888889 12.33333333 14.         35.        ]
 [ 7.28571429 15.2        33.5        12.5       ]
 [ 9.77777778 34.33333333 32.75       41.66666667]]


Q4. Write a Python script to verify that A is a magic square by constructing the 5-column array with column sums
of A and computing the maximum and minimum values of the column sums array. Do the same for the row
sums. Finally, compute the two diagonal sums. Check that these six values are the same.

In [187]:
A = np.array([[17, 24, 1, 8, 15], [23, 5, 7, 14, 16], [4, 6, 13, 20, 22], [10, 12, 19, 21, 3], [11, 18, 25, 2, 9]])

column_sums = np.sum(A, axis=0)
row_sums = np.sum(A, axis=1)

diag_sum1 = np.trace(A)
diag_sum2 = np.trace(np.fliplr(A))

is_column_sums_equal = np.all(column_sums == column_sums[0])

is_row_sums_equal = np.all(row_sums == row_sums[0])

is_magic_square = is_column_sums_equal and is_row_sums_equal and (column_sums[0] == row_sums[0] == diag_sum1 == diag_sum2)

print("Matrix A:\n", A)
print("Column sums of A:\n", column_sums)
print("Row sums of A:\n", row_sums)
print("Diagonal sums of A:\n", diag_sum1, diag_sum2)
print("Is A a magic square?\n", is_magic_square)


Matrix A:
 [[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]
Column sums of A:
 [65 65 65 65 65]
Row sums of A:
 [65 65 65 65 65]
Diagonal sums of A:
 65 65
Is A a magic square?
 True
