## Q.1

In [1]:
import numpy as np

In [6]:
def svmClassifier(support_vectors, targets):
    # Convert the support vectors and targets to NumPy arrays
    support_vectors = np.array(support_vectors)
    targets = np.array(targets)

    # Find the indices of positive and negative support vectors
    pos_indices = np.where(targets == 1)[0]
    neg_indices = np.where(targets == -1)[0]

    # Calculate the weight vector and bias
    weight_vector = np.sum(support_vectors[pos_indices], axis=0) 
    - np.sum(support_vectors[neg_indices], axis=0)
    bias = np.sum(np.linalg.norm(support_vectors[pos_indices], axis=1)) 
    - np.sum(np.linalg.norm(support_vectors[neg_indices], axis=1))

    # Normalize the weight vector
    weight_vector /= np.linalg.norm(weight_vector)

    # Construct the hyperplane equation
    hyperplane_equation = f"({weight_vector[0]})*x + ({weight_vector[1]})*y + ({bias}) = 0"

    return hyperplane_equation

In [3]:
# User input for support vectors
num_support_vectors = int(input("Enter the number of support vectors: "))
support_vectors = []
targets = []

for i in range(num_support_vectors):
    vector = input(f"Enter support vector {i+1} (x, y): ").split(",")
    x, y = float(vector[0]), float(vector[1])
    support_vectors.append((x, y))
    target = int(input(f"Enter the target for support vector {i+1} (+1 or -1): "))
    targets.append(target)

Enter the number of support vectors: 3
Enter support vector 1 (x, y): 2.5,0
Enter the target for support vector 1 (+1 or -1): 1
Enter support vector 2 (x, y): 0,3.5
Enter the target for support vector 2 (+1 or -1): 1
Enter support vector 3 (x, y): 7.5,7.5
Enter the target for support vector 3 (+1 or -1): -1


In [7]:
hyperplane_equation = svmClassifier(support_vectors, targets)
print(f"The equation of the hyperplane is: \n {hyperplane_equation}")

The equation of the hyperplane is: 
 (0.5812381937190965)*x + (0.813733471206735)*y + (6.0) = 0


## Q.2

In [14]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Load the data
data = np.genfromtxt('Nitrous_Oxide.csv', delimiter=',', skip_header=1)
X = data[:, 1:]  # Features (humidity, temperature, pressure)
y = data[:, 0]   # Target (nitrous oxide)
print(X)
print(y)

[[ 72.4   76.3   29.18]
 [ 41.6   70.3   29.35]
 [ 34.3   77.1   29.24]
 [ 35.1   68.    29.27]
 [ 10.7   79.    29.78]
 [ 12.9   67.4   29.39]
 [  8.3   66.8   29.48]
 [ 20.1   76.9   29.48]
 [ 72.2   77.7   29.09]
 [ 24.    67.7   29.6 ]
 [ 23.2   76.8   29.38]
 [ 47.4   86.6   29.38]
 [ 31.5   76.9   29.63]
 [ 10.6   86.3   29.56]
 [ 11.2   86.    29.48]
 [ 73.3   76.3   29.4 ]
 [ 75.4   77.9   29.28]
 [ 96.6   78.7   29.29]
 [107.4   86.8   29.03]
 [ 54.9   70.9   29.37]]
[0.9  0.91 0.96 0.89 1.   1.1  1.15 1.03 0.77 1.07 1.07 0.94 1.1  1.1
 1.1  0.91 0.87 0.78 0.82 0.95]


In [15]:
# Create the Linear Regression model
model = LinearRegression()

# Fit the model to the data
model.fit(X, y)

# Get the coefficients and intercept
coefficients = model.coef_
intercept = model.intercept_

# Print the model equation
print("Linear Regression Model:")
print(f"Nitrous Oxide = {intercept:.2f} + {coefficients[0]:.2f} * Humidity + {coefficients[1]:.2f} * Temperature + {coefficients[2]:.2f} * Pressure")

Linear Regression Model:
Nitrous Oxide = -2.23 + -0.00 * Humidity + 0.00 * Temperature + 0.11 * Pressure


In [9]:
# Conditions for estimation
humidity = float(input("Enter Humidity Value :"))#50.0
temperature = float(input("Enter Temperature Value :"))#76.0
pressure = float(input("Enter Pressure Value :")) #29.30

# Estimate nitrous oxide emission
nitrous_oxide = intercept + coefficients[0] * humidity + coefficients[1] * temperature + coefficients[2] * pressure

print(f"\nEstimated Nitrous Oxide Emission: {nitrous_oxide:.2f} ppm")

Enter Humidity Value :50
Enter Temperature Value :76
Enter Pressure Value :29.30

Estimated Nitrous Oxide Emission: 0.94 ppm
