In [13]:
import numpy as np

In [18]:
# Get input for the number of samples and features
num_samples = int(input("Enter the number of samples (i.e., number of rows): "))
num_features = int(input("Enter the number of features(i.e., X1, X2...Xn): "))

Enter the number of samples: 6
Enter the number of features: 2


In [19]:
# Get input for the feature matrix X
X = np.zeros((num_samples, num_features + 1))  # Add an extra column for the bias term
X[:, 0] = 1  # Set the bias term to 1
for i in range(num_samples):
    for j in range(1, num_features + 1):
        X[i, j] = float(input(f"Enter X[{i}][{j - 1}]: "))
print(X)

Enter X[0][0]: 1.6
Enter X[0][1]: 851
Enter X[1][0]: 22.0
Enter X[1][1]: 1058
Enter X[2][0]: 33
Enter X[2][1]: 1357
Enter X[3][0]: 15.5
Enter X[3][1]: 816
Enter X[4][0]: 43
Enter X[4][1]: 1201
Enter X[5][0]: 40
Enter X[5][1]: 1115
[[1.000e+00 1.600e+00 8.510e+02]
 [1.000e+00 2.200e+01 1.058e+03]
 [1.000e+00 3.300e+01 1.357e+03]
 [1.000e+00 1.550e+01 8.160e+02]
 [1.000e+00 4.300e+01 1.201e+03]
 [1.000e+00 4.000e+01 1.115e+03]]


In [20]:
# Get input for the response variable Y
Y = np.zeros(num_samples)
for i in range(num_samples):
    Y[i] = float(input(f"Enter Y[{i}]: "))


Enter Y[0]: 193
Enter Y[1]: 172
Enter Y[2]: 113
Enter Y[3]: 230
Enter Y[4]: 91
Enter Y[5]: 125


In [24]:
# Calculate the coefficients using the normal equations
XTX_inv = np.linalg.pinv(X.T @ X)
XTY = X.T @ Y
beta = XTX_inv @ XTY

# Print the coefficients
print("Coefficients (Beta):", beta[1:])
print("Intercept (Beta_0):", beta[0])

Coefficients (Beta): [-1.27199445 -0.15390423]
Intercept (Beta_0): 350.99427063050865


In [23]:
# Make predictions on the input data
Y_pred = np.dot(X, beta)

# Evaluate the model
e =(Y - Y_pred)
print("Error:", e)
mse =np.mean(Y - Y_pred)
print("Error:", mse)

Mean Squared Error: [-24.98657695  11.8202861   12.82959079  24.30749772 -20.45952512
  -3.51127254]
